[HIMDBVersion]
2.0
[DATABASE_VERSION]
"1.1" 
[SESSIONS_]
"DefaultSession" 
[CONFIGURATIONS]
"Flash_Debug" 
"Flash_Testing" 
"Gratis_Debug" 
"Gratis_Release" 
"Gratis_Testing" 
"Switch_Debug" 
"Switch_Testing" 
[CURRENT_CONFIGURATION]
"Switch_Testing" 
[CURRENT_SESSION]
"DefaultSession" 
[GENERAL_DATA_PROJECT]
"FDT_UserBootAreaFiles" "" 
[GENERAL_DATA_CONFIGURATION_Flash_Debug]
"PROJECT_FILES_MODIFIED_DATA_TAG" "TRUE" 
[SESSIONS_Flash_Debug]
"DefaultSession" 
[GENERAL_DATA_CONFIGURATION_Flash_Testing]
"PROJECT_FILES_MODIFIED_DATA_TAG" "TRUE" 
[SESSIONS_Flash_Testing]
"DefaultSession" 
[GENERAL_DATA_CONFIGURATION_Gratis_Debug]
"PROJECT_FILES_MODIFIED_DATA_TAG" "TRUE" 
[SESSIONS_Gratis_Debug]
"DefaultSession" 
[GENERAL_DATA_CONFIGURATION_Gratis_Release]
"PROJECT_FILES_MODIFIED_DATA_TAG" "TRUE" 
[SESSIONS_Gratis_Release]
"DefaultSession" 
[GENERAL_DATA_CONFIGURATION_Gratis_Testing]
"PROJECT_FILES_MODIFIED_DATA_TAG" "TRUE" 
[SESSIONS_Gratis_Testing]
"DefaultSession" 
[GENERAL_DATA_CONFIGURATION_Switch_Debug]
"PROJECT_FILES_MODIFIED_DATA_TAG" "TRUE" 
[SESSIONS_Switch_Debug]
"DefaultSession" 
[GENERAL_DATA_CONFIGURATION_Switch_Testing]
"PROJECT_FILES_MODIFIED_DATA_TAG" "FALSE" 
[SESSIONS_Switch_Testing]
"DefaultSession" 
[GENERAL_DATA_CONFIGURATION_SESSION_Switch_Debug_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_Gratis_Release_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_Gratis_Debug_DefaultSession]
[GENERAL_DATA_SESSION_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_Gratis_Testing_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_Switch_Testing_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_Flash_Testing_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_Flash_Debug_DefaultSession]
[END]
